
baseURL = 'https://KunalMaverick.github.io/'
languageCode = 'en-us'
title = 'Maverick Den'

[module]
  [[module.imports]]
    path = "github.com/hugo-sid/hugo-blog-awesome"

[params]
  goToTop = true

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/KunalMaverick"

[[params.socialIcons]]
  name = "x"
  url = "https://x.com/DeVere_Maverick"

[[params.socialIcons]]
  name = "email"
  url = "mailto:kunalkishoremaverick@gmail.com"  # Replace with your actual email address

[[params.socialIcons]]
  name = "googlescholar"
  url = "https://scholar.google.com/citations?user=RN5vKA8AAAAJ&hl=en"  # Replace with your Google Scholar ID

